'use strict';const test=require('node:test'),assert=require('node:assert/strict'),W=require('../domain/proofWorkflow');const{readiness,requireProviders}=require('../services/providerBoundary');const hash=c=>c.repeat(64);
function evidence(overrides={}){return{sourceId:'r1',sourceType:'verified_review',sourceDigest:hash('a'),authoritativeRef:'g2:r1',observedAt:'2026-07-01T00:00:00Z',subjectId:'customer-1',consentRef:'consent-1',consentAt:'2026-06-30T00:00:00Z',rights:{licenseId:'license-1',allowedUse:'social-proof publication',evidenceDigest:hash('b'),expiresAt:'2027-01-01T00:00:00Z'},...overrides};}
function versionInput(overrides={}){return{projectId:'p1',version:'v1',locale:'en-US',brandRuleVersion:'brand-1',brandPolicy:{allowedColors:['#123456'],forbiddenTerms:['guaranteed']},aiGenerated:true,disclosurePolicy:{label:'AI-assisted edit',watermark:true},assets:[{assetId:'quote',kind:'image',evidenceDigest:hash('c'),altText:'Customer quote card'},{assetId:'video',kind:'video',evidenceDigest:hash('d'),transcriptRef:'transcript-1'}],timeline:[{assetId:'video',track:'video',startMs:0,endMs:5000},{assetId:'quote',track:'overlay',startMs:500,endMs:3000}],...overrides};}
test('evidence ingestion requires authoritative provenance, current rights, and active consent',()=>{assert.equal(W.validateEvidence(evidence(),'2026-07-18T00:00:00Z').ok,true);const bad=W.validateEvidence(evidence({consentWithdrawnAt:'2026-07-02T00:00:00Z',rights:{...evidence().rights,expiresAt:'2026-01-01T00:00:00Z'}}),'2026-07-18T00:00:00Z');assert.equal(bad.ok,false);assert.match(bad.errors.join(' '),/withdrawn/);assert.match(bad.errors.join(' '),/expired/);});
test('sensitive customer attributes are prohibited from targeting evidence',()=>{const result=W.validateEvidence(evidence({containsSensitiveAttributes:true}));assert.equal(result.ok,false);assert.match(result.errors.join(' '),/sensitive/);});
test('content versions enforce editable timing, accessibility, brand, locale, and evidence',()=>{const ok=W.createVersion(versionInput());assert.equal(ok.ok,true);assert.match(ok.version.versionDigest,/^[a-f0-9]{64}$/);const input=versionInput();input.assets[0].altText='';input.timeline[1]={assetId:'missing',track:'video',startMs:100,endMs:1000};const bad=W.createVersion(input);assert.equal(bad.ok,false);assert.match(bad.errors.join(' '),/alt text/);assert.match(bad.errors.join(' '),/timeline/);});
test('consented CRM customers are assigned using allow-listed versioned segment rules',()=>{const input={ruleVersion:'seg-1',segments:[{id:'enterprise-renewal',rules:[{field:'plan',operator:'eq',value:'enterprise'},{field:'lifecycleStage',operator:'in',value:['renewal']}]}],customers:[{customerId:'c1',sourceDigest:hash('a'),marketingConsent:true,plan:'enterprise',lifecycleStage:'renewal'}]};const result=W.segmentCustomers(input);assert.deepEqual(result.assignments[0].segmentIds,['enterprise-renewal']);assert.match(result.segmentationDigest,/^[a-f0-9]{64}$/);assert.throws(()=>W.segmentCustomers({...input,customers:[{...input.customers[0],health:'condition'}]}),/sensitive/);});
test('testimonial selection is explainable, deterministic, consented, and moderated',()=>{const input={segmentId:'enterprise',selectionRuleVersion:'select-1',candidates:[{testimonialId:'t2',evidenceDigest:hash('b'),consentActive:true,moderationStatus:'approved',scores:{relevance:80,recency:90,verifiedOutcome:100,quality:90}},{testimonialId:'t1',evidenceDigest:hash('a'),consentActive:true,moderationStatus:'approved',scores:{relevance:100,recency:90,verifiedOutcome:100,quality:90}}]};const result=W.selectTestimonials(input);assert.equal(result.ranked[0].testimonialId,'t1');assert.match(result.ranked[0].reasons[0],/relevance/);assert.throws(()=>W.selectTestimonials({...input,candidates:[{...input.candidates[0],consentActive:false}]}),/eligible/);});
test('render requests and quality measurements are deterministic and comprehensive',()=>{const version=W.createVersion(versionInput()).version,spec={format:'mp4',preset:'testimonial-h264',width:1080,height:1920,frameRate:30,rendererVersion:'render-1'};assert.deepEqual(W.renderRequest(version,spec),W.renderRequest(version,spec));const scores={sourceFidelity:100,timing:98,layout:97,accessibility:95,brand:99,multilingual:94,exportCompatibility:100},quality=W.quality(version,{evaluatorVersion:'eval-1',artifactDigest:hash('e'),scores});assert.equal(quality.evaluation.passed,true);assert.deepEqual(W.quality(version,{evaluatorVersion:'eval-1',artifactDigest:hash('e'),scores:{...scores,sourceFidelity:50}}).evaluation.failed,['sourceFidelity']);});
test('publication requires quality, moderation, live rights, disclosure, providers, and independent approval',()=>{const version=W.createVersion(versionInput()).version,evaluation=W.quality(version,{evaluatorVersion:'e1',artifactDigest:hash('a'),scores:{sourceFidelity:100,timing:100,layout:100,accessibility:100,brand:100,multilingual:100,exportCompatibility:100}}).evaluation,input={project:{id:1,state:'review_pending',createdBy:1},version,evaluation,evidence:[{assetId:'a1',evidenceDigest:hash('b'),expiresAt:'2027-01-01',consentActive:true}],moderation:{decision:'approved',evidenceDigest:hash('c')},approval:{approvedBy:2,attestationDigest:hash('d')},providers:['storage_cdn','publishing'],now:'2026-07-18'};assert.equal(W.approve(input).ok,true);const bad=W.approve({...input,approval:{approvedBy:1,attestationDigest:hash('d')},providers:['storage_cdn']});assert.match(bad.errors.join(' '),/independent/);assert.match(bad.errors.join(' '),/publishing/);});
test('workflow roles and retry ceiling prevent publication shortcuts',()=>{assert.equal(W.transition('draft','editing','creator').ok,true);assert.equal(W.transition('review_pending','approved','creator').ok,false);assert.equal(W.transition('review_pending','approved','reviewer').ok,true);assert.deepEqual(W.retry(1),{status:'retry',retryable:true,nextDelaySeconds:30});assert.deepEqual(W.retry(5),{status:'dead_letter',retryable:false,nextDelaySeconds:null});});
test('provider usage is evidence-bound',()=>{assert.match(W.usage({provider:'review_platform',operation:'crawl',units:40,unitType:'reviews',evidenceDigest:hash('a')}).usageDigest,/^[a-f0-9]{64}$/);assert.throws(()=>W.usage({provider:'unknown',operation:'x',units:1,unitType:'call',evidenceDigest:hash('a')}),/usage evidence/);});
test('all CRM, review, media, rights, storage, language, and publishing providers fail closed',()=>{assert.equal(readiness({}).ready,false);assert.throws(()=>requireProviders(['crm'],{}),/not ready/);const env={};for(const name of W.PROVIDERS){const key=name.toUpperCase();env[`${key}_PROVIDER_ENABLED`]='true';env[`${key}_PROVIDER_URL`]=`https://${name}.example.invalid`;env[`${key}_PROVIDER_TOKEN`]='runtime';}assert.equal(readiness(env).ready,true);});
